repos:
- repo: https://github.com/psf/black
  rev: "22.3.0"
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
      - id: flake8
        exclude: opentestframework/gui
        args: [--max-line-length=110, --exclude=venv]

- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=50000']
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: no-commit-to-branch
  - id: check-docstring-first
  - id: debug-statements
